name: 'Main'
on:
  - push

jobs:
  configure:
    runs-on: ubuntu-latest
    outputs:
      uid_gid: ${{ steps.get-user.outputs.uid_gid }}
      datetime: ${{ steps.get-datetime.outputs.datetime }}
    steps:
      - id: get-user
        run: echo "uid_gid=$(id -u):$(id -g)" >> $GITHUB_OUTPUT
      - id: get-datetime
        run: echo "datetime=$(date +'%Y%m%d%H%M%S')" >> $GITHUB_OUTPUT

  build:
    needs: [configure]
    runs-on: ubuntu-latest
    container:
      image: node:20-bookworm
      env:
        HEAD_SHA: ${{ github.event.pull_request.head.sha }}
        HEAD_BRANCH_NAME: ${{ github.head_ref }}
    steps:
      - name: Checkout
        uses: actions/checkout@v5
        with:
          submodules: true

      - name: Install node
        uses: actions/setup-node@v4
        with:
          registry-url: 'https://registry.npmjs.org'
          scope: '@zondax'

      - name: Setup pnpm
        uses: pnpm/action-setup@v4
        with:
          version: 11

      - run: pnpm install --frozen-lockfile

      - run: pnpm format:check

      - run: pnpm lint

      - run: pnpm test
