name: 'Main'
on:
  - push

jobs:
  configure:
    runs-on: ubuntu-latest
    outputs:
      uid_gid: ${{ steps.get-user.outputs.uid_gid }}
      datetime: ${{ steps.get-datetime.outputs.datetime }}
    steps:
      - id: get-user
        run: echo "uid_gid=$(id -u):$(id -g)" >> $GITHUB_OUTPUT
      - id: get-datetime
        run: echo "datetime=$(date +'%Y%m%d%H%M%S')" >> $GITHUB_OUTPUT

  build:
    needs: [configure]
    runs-on: ubuntu-latest
    container:
      image: node:20-bookworm
      env:
        HEAD_SHA: ${{ github.event.pull_request.head.sha }}
        HEAD_BRANCH_NAME: ${{ github.head_ref }}
    steps:
      - name: Checkout
        uses: actions/checkout@v5
        with:
          submodules: true

      - name: Install node
        uses: actions/setup-node@v4
        with:
          registry-url: 'https://registry.npmjs.org'
          scope: '@zondax'

      - uses: oven-sh/setup-bun@v1

      - name: Install build dependencies
        run: |
          apt-get update
          apt-get install -y build-essential python3 libusb-1.0-0-dev libudev-dev
          npm install -g node-gyp node-gyp-build

      - run: bun install

      - run: bun run format:check

      - run: bun lint

      - run: bun test
